#!/bin/sh

. /etc/init.d/project-shell-functions

NAME=$(get_script_name $0)
load_defaults $NAME

. $UDEV_CONFIG

case "$1" in
	start)
		report_info "Populating ${udev_root:-/dev} using udev: "
		printf '\000\000\000\000' > /proc/sys/kernel/hotplug
		/sbin/udevd --daemon
		report_ok_fail
		[[ $? -ne 0 ]] && exit $?
		udevadm trigger --type=subsystems --action=add
		udevadm trigger --type=devices --action=add
		report_info "Running udevadm settle .."
		udevadm settle --timeout=30
		report_ok_fail
		;;
	stop)
		udevadm control --stop-exec-queue
		killall udevd
		;;
	status|restart)
		report_info "$NAME: $1 is not implemented"
		;;
	*)
		usage
esac
