#! /bin/sh

. /etc/init.d/project-shell-functions

NAME=$(get_script_name $0)
load_defaults $NAME

[[ -d /run/network ]] || mkdir /run/network

case "$1" in
  start)
    report_info "Starting $NAME .."
    ifup $DAEMON_ARGS
    report_ok_fail
    ;;
  stop)
    report_info "Stopping $NAME: "
    ifdown $DAEMON_ARGS
    report_ok_fail
    ;;
  *)
    echo "Usage: $0 {start|stop}" >&2
    exit 1
esac
